using System.ComponentModel.DataAnnotations.Schema;

namespace _02_OverrideConfigurationByDataAnnotations.Entities
{
    [Table("tblComments")]
    public class Comment
    {
        [Column("CommentId")] // This attribute is used to specify the column name in the database that will be used for this property
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This attribute is used to specify that the value of the column is generated by the database
        public int Id { get; set; }
        public int TweetId { get; set; }
        public int UserId { get; set; }
        public string CommentText { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
