using System;

namespace Main
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Hello, World");
            Console.WriteLine("My Name Is Mahmoud Mattar");

            Console.Write("I'm Learning C#");
            Console.Write(" It Is an Easy Language To Learn");
            Console.Write(" The Sum Of 10 + 10 Is: " + (10 + 10));

            Console.ReadKey();
        }
    }
}